---
version: 1
settings:
  providers:
    argo-aoa:
      entries: '.entries["{{ .Name }}"][0] | .version'
      evaluator: '{{ .Selector }} | to_entries | .[] | select(.value.chartName!=null and .value.repoURL!=null and .value.targetRevision!=null) | [{"chartName": .value.chartName, "repoURL": .value.repoURL, "targetRevision": .value.targetRevision}]'
      selector: '.sample.applications'

  authentication: {}

  notifiers:
    github:
      enabled: false
      title: "[Abyssal] Bump {{ .Target }} from v{{ .CurrentVersion }} to v{{ .NewVersion }}"
      body: |
        Bump {{ .Target }} from v{{ .CurrentVersion }} to v{{ .NewVersion }}.
      token: "{{ .EnvironmentVariables.GITHUB_TOKEN }}"
      labels: ["abyssal"]
      organization: "{{ .EnvironmentVariables.GITHUB_ORGANIZATION }}"
      repository: "{{ .EnvironmentVariables.GITHUB_REPOSITORY }}"
    slack:
      enabled: false
      webhook: "{{ .EnvironmentVariables.SLACK_WEBHOOK }}"
      title: "[Abyssal] Bump {{ .Target }} from v{{ .CurrentVersion }} to v{{ .NewVersion }}"
      body: |
        Bump {{ .Target }} from v{{ .CurrentVersion }} to v{{ .NewVersion }}.
      username: "Abyssal"
      iconEmoji: ":robot_face:"
      channel: "#abyssal-notifications"
    discord:
      enabled: false
      webhook: "{{ .EnvironmentVariables.DISCORD_WEBHOOK }}"
      title: "[Abyssal] Bump {{ .Target }} from v{{ .CurrentVersion }} to v{{ .NewVersion }}"
      body: |
        Bump {{ .Target }} from v{{ .CurrentVersion }} to v{{ .NewVersion }}.
      username: "Abyssal"
      avatarURL: "https://avatars.githubusercontent.com/u/123456789?v=4"
    email:
      enabled: false
      smtpHost: "{{ .EnvironmentVariables.SMTP_HOST }}"
      smtpPort: "{{ .EnvironmentVariables.SMTP_PORT }}"
      smtpUser: "{{ .EnvironmentVariables.SMTP_USER }}"
      smtpPassword: "{{ .EnvironmentVariables.SMTP_PASSWORD }}"
      from: "{{ .EnvironmentVariables.SMTP_FROM }}"
    jira:
      enabled: false
      title: "[Abyssal] Bump {{ .Target }} from v{{ .CurrentVersion }} to v{{ .NewVersion }}"
      body: |
        Bump {{ .Target }} from v{{ .CurrentVersion }} to v{{ .NewVersion }}.
      user: "{{ .EnvironmentVariables.JIRA_USER }}"
      token: "{{ .EnvironmentVariables.JIRA_TOKEN }}"
      url: "{{ .EnvironmentVariables.JIRA_URL }}"
      project: "{{ .EnvironmentVariables.JIRA_PROJECT }}"
      issueType: "{{ .EnvironmentVariables.JIRA_ISSUE_TYPE }}"
      labels: ["abyssal"]


providers:
  - type: argo-aoa # following the argo app of apps pattern
    directory: "."
    selector: '.sample.applications'
    nameFrom: 'chartName'
