---
version: 1
settings:
  providers:
    argo-aoa:
      entries: '.entries["{{ .Name }}"][0] | .version'
      evaluator: '{{ .Selector }} | to_entries | .[] | select(.value.chartName!=null and .value.repoURL!=null and .value.targetRevision!=null) | [{"chartName": .value.chartName, "repoURL": .value.repoURL, "targetRevision": .value.targetRevision}]'
      selector: '.sample.applications'

  authentication: {}

  notifiers:
    - type: github
      enabled: true
      title: "[Abyssal] Bump {{ .Target.Name }} from v{{ .CurrentVersion }} to v{{ .ExpectedVersion }}"
      body: |
        Bump {{ .Target.Name }} from v{{ .CurrentVersion }} to v{{ .ExpectedVersion }}.
      token: "{{ .EnvironmentVariables.GITHUB_TOKEN }}"
      labels: ["abyssal"]
      organization: "{{ .EnvironmentVariables.GITHUB_ORGANIZATION }}"
      repository: "{{ .EnvironmentVariables.GITHUB_REPOSITORY_NAME }}"

providers:
  - type: argo-aoa # following the argo app of apps pattern
    directory: "."
    selector: '.sample.applications'
