---
name: Abyssal CI
on:
  workflow_dispatch:
    inputs:
      abyssal-version:
        description: 'Abyssal version to use'
        required: false
        default: 'latest'
  schedule:
    - cron: 0 0 * * *

permissions: {}
jobs:
  abyssal:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: camalot/abyssal-setup@develop
        with:
          abyssal-version: '${{ github.event.inputs.abyssal-version }}'

      - name: Run Abyssal
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ORGANIZATION: camalot
          GITHUB_REPOSITORY: abyssal-test
        run: |
          abyssal action --config ${{ github.workspace }}/.github/abyssal/.abyssal.yaml >> "$GITHUB_STEP_SUMMARY"